//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampoORG.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geolocalizacion
    {
        public int IdGeolocalizacion { get; set; }
        public string Dispositivo { get; set; }
        public string DicrecionIP { get; set; }
        public string Hora { get; set; }
    }
}
